# Generated by Django 3.2.2 on 2021-05-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
    ]
