# Generated by Django 3.2.2 on 2021-05-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accounts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'managed': False},
        ),
    ]
