# Generated by Django 3.2.2 on 2021-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accounts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decryp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('salt', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'decryp',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='accounts',
            options={'managed': True},
        ),
    ]
