# Generated by Django 3.2.2 on 2021-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210521_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='salt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
